export type PlannerErrorCode =
  | 'NO_ELIGIBLE_EXERCISE'
  | 'REQUIRED_MOVEMENT_SLOT_UNFILLED'
  | 'SESSION_DURATION_UNSATISFIABLE'
  | 'UNSUPPORTED_TRAINING_SCHEDULE'
  | 'INVALID_EXERCISE_LIBRARY'
  | 'PROGRAMME_SCHEMA_VALIDATION_FAILED'
  | 'INVALID_SET_PRESCRIPTION'
  | 'CALENDAR_UNSATISFIABLE'
  | 'STRATEGY_UNSATISFIABLE'
  | 'NO_ELIGIBLE_EXERCISE_FOR_REQUIRED_SLOT'
  | 'NO_VALID_MODIFICATION_FOR_REQUIRED_SLOT'
  | 'EXERCISE_LIBRARY_METADATA_INSUFFICIENT'
  | 'SESSION_MOVEMENT_COVERAGE_IMPOSSIBLE'
  | 'SESSION_DURATION_REPAIR_FAILED'
  | 'SESSION_SEQUENCE_UNSATISFIABLE'
  | 'SESSION_FINALIZATION_FAILED'
  | 'PROGRAMME_REPAIR_FAILED'
  | 'PROGRAMME_REPAIR_EXHAUSTED'
  | 'PROGRAMME_GENERATION_DEADLINE_EXCEEDED'
  | 'PROGRAMME_VALIDATION_UNSUPPORTED_VERSION';

export class PlannerError extends Error {
  readonly code: PlannerErrorCode;
  readonly details: unknown;

  constructor(
    code: PlannerErrorCode,
    message: string,
    details: unknown = null,
  ) {
    super(message);
    this.name = 'PlannerError';
    this.code = code;
    this.details = details;
  }
}
